# Build stage
FROM node:20 AS build-stage
WORKDIR /app
COPY frontend .

RUN npm install && npm run build


# Production stage
FROM nginx:stable-alpine AS production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html/

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/servers/https-server.conf /etc/nginx/servers/https-server.conf

RUN	mkdir -p /etc/nginx/ssl && \
	echo -e "$CERT_KEY" > /etc/nginx/ssl/transcendance.key && \
	echo -e "$CERT_CRT" > /etc/nginx/ssl/transcendance.crt && \
	chmod 600 /etc/nginx/ssl/transcendance.key && \
	chmod 600 /etc/nginx/ssl/transcendance.crt && \
	chown nginx:nginx /etc/nginx/ssl/transcendance.key && \
	chown nginx:nginx /etc/nginx/ssl/transcendance.crt
	
EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]